version: '3.8'

services:
  db:
    image: pgrouting/pgrouting:17-3.5-main
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    container_name: spdb_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  app:
    build:
      context: ./app
    container_name: streamlit-app
    restart: unless-stopped
    ports:
      - "8501:8501"
    depends_on:
      - db
      - importer
    environment:
      DATABASE_URL: postgres://bikeuser:bikepass@db:5432/bikedb # todo change this to env var

  importer:
    build:
      context: ./db/osm_imports
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      PG_HOST: db
      PG_PASSWORD: ${POSTGRES_PASSWORD}
      PG_USER: ${POSTGRES_USER}
    volumes:
      - ./data:/data

volumes:
  db-data:
