[project]
name = "spdb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "folium>=0.19.5",
    "geopy>=2.4.1",
    "streamlit>=1.45.0",
    "streamlit-folium>=0.25.0",
    "streamlit-modal>=0.1.2",
    "streamlit-option-menu>=0.4.0",
]
